// AUTO-GENERATED by scripts/fetch-rates.mjs — do not edit manually.
// 重新生成：pnpm rates
export const ratesUpdatedAt = "2026-09-26";
export const ratesProvider = "open.er-api.com（ExchangeRate-API 备用源）";
export const cnyPerUnit: Record<string, number> = {
  人民币: 1,
  加元: 4.753161,
  匈牙利福林: 0.02098,
  印度卢比: 0.070138,
  捷克克朗: 0.314231,
  新西兰元: 3.806891,
  新谢克尔: 2.206552,
  日元: 0.042639,
  智利比索: 0.006981,
  欧元: 7.655304,
  波兰兹罗提: 1.750442,
  泰铢: 0.201239,
  澳元: 4.720979,
  美元: 6.715721,
  英镑: 8.894969,
  菲律宾比索: 0.107371,
  韩元: 0.004942,
  马来西亚林吉特: 1.648014,
  墨西哥比索: 0.380241,
};
