// AUTO-GENERATED by scripts/fetch-rates.mjs — do not edit manually.
// 重新生成：pnpm rates
export const ratesUpdatedAt = "2026-09-23";
export const ratesProvider = "Frankfurter（欧洲央行 ECB 参考汇率）";
export const cnyPerUnit: Record<string, number> = {
  人民币: 1,
  加元: 4.760714,
  印度卢比: 0.070058,
  新西兰元: 3.817547,
  日元: 0.042474,
  欧元: 7.6538,
  澳元: 4.740369,
  美元: 6.707388,
  英镑: 8.904945,
  韩元: 0.004913,
};
